spring.application.name=BIM-API-PRACTICE-TEST

spring.profiles.active=${APP_PROFILE:dev}
logging.config=classpath:logback.xml
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Maputo