
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Maputo
spring.jpa.hibernate.ddl-auto=update


#geo location apis
geo.base.url=${GEO_BASE_URL}
geo.search=${GEO_SEARCH}

geo.api.default.language=${GEO_API_LANGUAGE:pt}
geo.api.default.response.format=${GEO_API_RESPONSE_FORMAT:json}

#weather apis
weather.base.url=${WEATHER_BASE_URL}
weather.forecast=${WEATHER_FORECAST}

