
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASS}
spring.jpa.properties.hibernate.jdbc.time_zone=Africa/Maputo
spring.jpa.hibernate.ddl-auto=update


#geo apis
geo.base.url=${GEO_BASE_URL}
geo.search=${GEO_SEARCH}

geo.api.language=${GEO_API_LANGUAGE:pt}
geo.api.response.format=${GEO_API_RESPONSE_FORMAT:json}

#wheather apis
wheather.base.url=${WHEATHER_BASE_URL}
wheather.forecast=${WHEATHER_FORECAST}

